openapi: 3.0.1
info:
  title: DFlow Market Maker EVM Standard Swap API
  version: 0.1.1
  description: An API for interacting with a DFlow market maker to retrieve quotes for EVM Standard Swaps.

paths:
  /indicativeQuote:
    get:
      summary: Retrieve an indicative quote
      parameters:
        - name: sendToken
          description: Address of the ERC-20 token that the retail trader is sending. If specified as 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, the retail trader sends the unwrapped variant of the native token, and the maker receives the wrapped variant.
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SchemaAddress'
        - name: receiveToken
          description: Address of the ERC-20 token that the retail trader is receiving. If specified as 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, the retail trader receives the unwrapped variant variant of the native token, and the maker sends the wrapped variant.
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SchemaAddress'
        - name: minFillPrice
          description: Minimum allowed fill price. Specified as token units sent to retail trader per token received from retail trader
          in: query
          required: true
          schema:
            type: string
            pattern: '^0$|^[1-9]\d*$'
        - name: auctionId
          description: The auction ID associated with this request
          in: query
          required: true
          schema:
            type: string
            pattern: '^0$|^[1-9]\d*$'
        - name: auctionEpoch
          description: The auction epoch associated with this request
          in: query
          required: true
          schema:
            type: string
            pattern: '^0$|^[1-9]\d*$'
      responses:
        '200':
          description: Indicative quote details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndicativeQuoteGetResponse'
        default:
          description: The market maker did not provide an indicative quote
          content:
            application/json:
              schema:
                type: object

  /firmQuote:
    post:
      summary: Retrieve a firm quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FirmQuotePostRequest'
      responses:
        '200':
          description: Firm quote response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirmQuotePostResponse'
        default:
          description: The market maker did not provide a firm quote due to an unexpected error
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    SchemaAddress:
      type: string
      pattern: '^0x[0-9a-fA-F]{40}$'

    Eip712ObjectProperty:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
      required:
        - name
        - type

    Eip712Domain:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        chainId:
          type: string
        verifyingContract:
          type: string
      required:
        - name
        - version
        - chainId
        - verifyingContract

    Eip712TypedDataWithoutMessage:
      type: object
      properties:
        types:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/Eip712ObjectProperty'
        domain:
          $ref: '#/components/schemas/Eip712Domain'
        primaryType:
          type: string
      required:
        - types
        - domain
        - primaryType

    IndicativeQuoteGetResponse:
      type: object
      properties:
        fillPrice:
          description: Token units sent to retail trader per token received from retail trader. Must be greater than or equal to the minFillPrice.
          type: string
          pattern: '^0$|^[1-9]\d*$'
      required:
        - fillPrice

    FirmQuotePostRequest:
      type: object
      properties:
        sendToken:
          description: Address of the ERC-20 token that the retail trader is sending. If specified as 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, the retail trader sends the unwrapped variant of the native token, and the maker receives the wrapped variant.
          $ref: '#/components/schemas/SchemaAddress'
        receiveToken:
          description: Address of the ERC-20 token that the retail trader is receiving. If specified as 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, the retail trader receives the unwrapped variant variant of the native token, and the maker sends the wrapped variant.
          $ref: '#/components/schemas/SchemaAddress'
        takerToken:
          description: takerToken to use when constructing the DFlow Swap order. Not specified if the retail trader is sending the unwrapped variant of the native token.
          $ref: '#/components/schemas/SchemaAddress'
        makerToken:
          description: makerToken to use when constructing the DFlow Swap order. Not specified if the retail trader is receiving the unwrapped variant of the native token.
          $ref: '#/components/schemas/SchemaAddress'
        sendQty:
          description: Send quantity specified as a scaled integer. This is the takerAmount to use when constructing the DFlow Swap order.
          type: string
          pattern: '^[1-9]\d*$'
        platformFee:
          description: Platform fee amount specified as a scaled integer. Specified if and only if a platform fee applies to the order. If specified, this is the platformFee to use when constructing the DFlow Swap order, and this amount of the receiveToken will be transfered from the maker to the platformFeeReceiver in addition to the fillQty being transfered from the maker to the taker.
          type: string
          pattern: '^0$|^[1-9]\d*$'
        platformFeeReceiver:
          description: Platform fee receiver address. Specified if and only if a platform fee applies to the order. If specified, this is the platformFeeReceiver to use when constructing the DFlow Swap order.
          $ref: '#/components/schemas/SchemaAddress'
        minFillQty:
          description: Minimum allowed fill quantity specified as a scaled integer. This is the minimum makerAmount to use when constructing the DFlow Swap order.
          type: string
          pattern: '^0$|^[1-9]\d*$'
        useMakerAmountAndTakerAmount:
          description: If true, the DFlow Swap order must be constructed using uint128 makerAmountAndTakerAmount where the higher-order bits are the uint128 makerAmount and the lower-order bits are the uint128 takerAmount. Otherwise, the order must be constructed using uint256 makerAmount and uint256 takerAmount.
          type: boolean
        retailTrader:
          description: Address of the retail trader's wallet
          $ref: '#/components/schemas/SchemaAddress'
        endorsement:
          description: The order flow source's endorsement of this request
          type: object
          properties:
            endorser:
              description: Base58-encoded Ed25519 public key used to sign the endorsement message.
              type: string
            signature:
              description: Base64-encoded Ed25519 signature of {id},{expirationTime},{data}
              type: string
            id:
              description: Base64-encoded 64-bit identifier for the endorsement.
              type: string
            expirationTimeUTC:
              description: Expiration time as UTC. Number of seconds since Jan 1, 1970 00:00:00 UTC.
              type: integer
            data:
              description: Pipe-delimited endorsement data
              type: string
          required:
            - endorser
            - signature
            - id
            - expirationTimeUTC
            - data
        taker:
          description: taker to use when constructing the DFlow Swap order
          $ref: '#/components/schemas/SchemaAddress'
        txOrigin:
          description: txOrigin to use when constructing the DFlow Swap order
          $ref: '#/components/schemas/SchemaAddress'
        minExpiry:
          description: Minimum allowed expiry for the DFlow Swap order. Number of seconds since Jan 1, 1970 00:00:00 UTC.
          type: integer
          minimum: 0
          maximum: 1099511627775  # Equivalent to 0xffffffffff in hexadecimal
        flags:
          description: uint256 flags to use when constructing the DFlow Swap order
          type: string
          pattern: '^0$|^[1-9]\d*$'
        nonceBucket:
          description: nonceBucket to use when constructing the DFlow Swap order
          type: string
          pattern: '^0$|^[1-9]\d*$'
        nonce:
          description: nonce to use when constructing the DFlow Swap order
          type: string
          pattern: '^0$|^[1-9]\d*$'
        eip712:
          description: EIP-712 TypedData that the market maker must sign. The market maker must construct a message to the primary type and produce an EIP-712 signature covering the TypedData.
          $ref: '#/components/schemas/Eip712TypedDataWithoutMessage'
        auctionId:
          description: The auction ID associated with this request
          type: string
          pattern: '^0$|^[1-9]\d*$'
        auctionEpoch:
          description: The auction epoch associated with this request
          type: string
          pattern: '^0$|^[1-9]\d*$'
      required:
        - sendToken
        - receiveToken
        - sendQty
        - minFillQty
        - useMakerAmountAndTakerAmount
        - retailTrader
        - endorsement
        - taker
        - txOrigin
        - minExpiry
        - flags
        - nonceBucket
        - nonce
        - eip712
        - auctionId
        - auctionEpoch

    FirmQuotePostResponse:
      type: object
      discriminator:
        propertyName: code
      oneOf:
        - $ref: '#/components/schemas/FirmQuoteResponseOk'
        - $ref: '#/components/schemas/FirmQuoteResponseRefused'

    FirmQuoteResponseOk:
      type: object
      properties:
        code:
          description: Ok
          type: integer
          enum: [0]
        fillQty:
          description: Fill quantity specified as a scaled integer. Must be greater than or equal to the minFillQty. This is the makerAmount used to construct the DFlow Swap order. This amount of the receiveToken is transfered from the maker to the taker.
          type: string
          pattern: '^0$|^[1-9]\d*$'
        maker:
          description: Address of the market maker's wallet. This is the signer of the DFlow Swap order. This is the maker used to construct the DFlow Swap order.
          $ref: '#/components/schemas/SchemaAddress'
        expiry:
          description: expiry used to construct the DFlow Swap order
          type: integer
          minimum: 0
          maximum: 1099511627775  # Equivalent to 0xffffffffff in hexadecimal
        orderSignature:
          description: Market maker's signature of the DFlow Swap order
          type: object
          properties:
            r:
              type: string
              pattern: '^0x[0-9a-fA-F]+$'
            s:
              type: string
              pattern: '^0x[0-9a-fA-F]+$'
            v:
              type: integer
            signatureType:
              type: integer
              enum: [2]
          required:
            - r
            - s
            - v
            - signatureType
        quoteId:
          description: The market maker's identifier for the quote
          type: string
      required:
        - code
        - fillQty
        - maker
        - expiry
        - orderSignature
        - quoteId

    FirmQuoteResponseRefused:
      type: object
      properties:
        code:
          description: The market maker refused to provide a firm quote
          type: integer
          enum: [1]
      required:
        - code
